// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cjymazhxxgpwysmhpyoq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNqeW1hemh4eGdwd3lzbWhweW9xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0ODI4MzksImV4cCI6MjA2NzA1ODgzOX0.cxb7car9jByzi3REnNILBqrCa8vqVxlN_1gJWHjdns0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});